const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,PUB=path.join(ROOT,'public'),DB=path.join(ROOT,'data','db.json'),PORT=process.env.PORT||3001,sessions=new Map();
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8')),write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2)),hash=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
function ensure(d){d.settings=d.settings||{};d.categories=d.categories||[];d.items=d.items||[];d.schools=d.schools||[];d.analytics=d.analytics||{visits:[],events:[],leads:[]};d.customers=d.customers||[];d.analytics.visits=d.analytics.visits||[];d.analytics.events=d.analytics.events||[];d.analytics.leads=d.analytics.leads||[];d.admin=d.admin||{email:'admin@together.local',passwordHash:hash('ChangeMe123!')};d.settings.company=d.settings.company||'Together Photographer';d.settings.phone=d.settings.phone||'01200396903';d.settings.logo=d.settings.logo||'/assets/logo-temp.jpg';d.settings.hero=d.settings.hero||'/assets/hero-concept.png';d.settings.taglineAr=d.settings.taglineAr||'تصوير مدرسي احترافي، تصميمات مميزة، وذكريات تدوم.';d.settings.taglineEn=d.settings.taglineEn||'Creative school photography, premium designs, and memories made to last.';return d}
function send(res,code,data,type='application/json'){res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN'});res.end(type.includes('json')?JSON.stringify(data):data)}
function body(req){return new Promise((ok,no)=>{let b='';req.on('data',c=>{b+=c;if(b.length>25e6)req.destroy()});req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch(e){no(e)}})})}
function auth(req){let m=(req.headers.cookie||'').match(/tp_session=([^;]+)/);return m&&sessions.get(m[1])}
function customerAuth(req){let m=(req.headers.cookie||'').match(/tp_customer=([^;]+)/);return m&&sessions.get('c:'+m[1])}
function mime(p){return ({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp','.webmanifest':'application/manifest+json'})[path.extname(p).toLowerCase()]||'application/octet-stream'}
function saveImage(s,prefix){let m=String(s||'').match(/^data:image\/(png|jpeg|webp);base64,(.+)$/);if(!m)return null;let ext=m[1]==='jpeg'?'jpg':m[1],name=`uploads/${prefix}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;fs.mkdirSync(path.join(PUB,'uploads'),{recursive:true});fs.writeFileSync(path.join(PUB,name),Buffer.from(m[2],'base64'));return '/'+name}
http.createServer(async(req,res)=>{let u=new URL(req.url,'http://x');try{
if(u.pathname==='/api/public'&&req.method==='GET'){let d=ensure(read());return send(res,200,{settings:d.settings,categories:d.categories,items:d.items,schools:d.schools})}
if(u.pathname==='/api/login'&&req.method==='POST'){let x=await body(req),d=ensure(read());if(String(x.email).toLowerCase()===String(d.admin.email).toLowerCase()&&hash(x.password)===d.admin.passwordHash){let t=crypto.randomBytes(24).toString('hex');sessions.set(t,{role:'admin'});res.setHeader('Set-Cookie',`tp_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);return send(res,200,{ok:true})}return send(res,401,{error:'Invalid login'})}
if(u.pathname==='/api/logout'){sessions.clear();res.setHeader('Set-Cookie','tp_session=; Path=/; Max-Age=0');return send(res,200,{ok:true})}
if(u.pathname==='/api/admin'&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read());return send(res,200,{...d,admin:{email:d.admin.email}})}
if(u.pathname==='/api/settings'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),x=await body(req);if(x.logoData){let p=saveImage(x.logoData,'logo');if(p)x.logo=p;delete x.logoData}if(x.heroData){let p=saveImage(x.heroData,'hero');if(p)x.hero=p;delete x.heroData}d.settings={...d.settings,...x};write(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/account'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),x=await body(req);if(!x.email)return send(res,400,{error:'Email required'});d.admin.email=String(x.email).trim();if(x.password)d.admin.passwordHash=hash(x.password);write(d);sessions.clear();return send(res,200,{ok:true})}
if(u.pathname==='/api/category'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),x=await body(req);x.id=x.id||crypto.randomUUID();let i=d.categories.findIndex(z=>z.id===x.id);if(i>=0)d.categories[i]={...d.categories[i],...x};else d.categories.push(x);write(d);return send(res,200,{ok:true,id:x.id})}
if(u.pathname.startsWith('/api/category/')&&req.method==='DELETE'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),id=u.pathname.split('/').pop();if(d.items.some(x=>x.category===id))return send(res,400,{error:'Category has designs'});d.categories=d.categories.filter(x=>x.id!==id);write(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/item'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),x=await body(req);x.id=x.id||crypto.randomUUID();if(x.imageData){let p=saveImage(x.imageData,'design');if(p)x.image=p;delete x.imageData}let i=d.items.findIndex(z=>z.id===x.id);if(i>=0)d.items[i]={...d.items[i],...x};else d.items.unshift(x);write(d);return send(res,200,{ok:true,id:x.id})}
if(u.pathname.startsWith('/api/item/')&&req.method==='DELETE'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),id=u.pathname.split('/').pop();d.items=d.items.filter(x=>x.id!==id);write(d);return send(res,200,{ok:true})}

if(u.pathname==='/api/track'&&req.method==='POST'){let d=ensure(read()),x=await body(req),now=new Date().toISOString(),vid=String(x.visitorId||'').slice(0,100);if(!vid)return send(res,400,{error:'visitorId required'});let v=d.analytics.visits.find(z=>z.visitorId===vid);if(!v){v={visitorId:vid,firstSeen:now,lastSeen:now,visits:1,pages:[String(x.page||'/').slice(0,200)],referrer:String(x.referrer||'').slice(0,500),userAgent:String(req.headers['user-agent']||'').slice(0,500)};d.analytics.visits.unshift(v)}else{v.lastSeen=now;v.visits=(v.visits||0)+1;let pg=String(x.page||'/').slice(0,200);v.pages=v.pages||[];if(!v.pages.includes(pg))v.pages.push(pg)}d.analytics.visits=d.analytics.visits.slice(0,5000);write(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/event'&&req.method==='POST'){let d=ensure(read()),x=await body(req);d.analytics.events.unshift({at:new Date().toISOString(),visitorId:String(x.visitorId||'').slice(0,100),type:String(x.type||'click').slice(0,50),label:String(x.label||'').slice(0,200),page:String(x.page||'/').slice(0,200)});d.analytics.events=d.analytics.events.slice(0,10000);write(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/lead'&&req.method==='POST'){let d=ensure(read()),x=await body(req);if(!x.email&&!x.phone)return send(res,400,{error:'Email or phone required'});d.analytics.leads.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),name:String(x.name||'').slice(0,150),email:String(x.email||'').slice(0,200),phone:String(x.phone||'').slice(0,100),message:String(x.message||'').slice(0,1000),visitorId:String(x.visitorId||'').slice(0,100)});d.analytics.leads=d.analytics.leads.slice(0,5000);write(d);return send(res,200,{ok:true})}

if(u.pathname==='/api/customer-signup'&&req.method==='POST'){let x=await body(req),d=ensure(read()),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||''),name=String(x.name||'').trim();if(!email||!email.includes('@'))return send(res,400,{error:'Valid email required'});if(password.length<6)return send(res,400,{error:'Password must be at least 6 characters'});if(d.customers.some(z=>String(z.email).toLowerCase()===email))return send(res,409,{error:'Email already registered'});let c={id:crypto.randomUUID(),name,email,passwordHash:hash(password),active:true,allowed:['all'],createdAt:new Date().toISOString(),selfRegistered:true,loginCount:0,lastLogin:null};d.customers.unshift(c);d.analytics.events.unshift({at:new Date().toISOString(),visitorId:String(x.visitorId||'').slice(0,100),type:'signup',label:email,page:'/catalog.html'});write(d);let t=crypto.randomBytes(24).toString('hex');sessions.set('c:'+t,{role:'customer',id:c.id,name:c.name,email:c.email,allowed:c.allowed});res.setHeader('Set-Cookie',`tp_customer=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);return send(res,200,{ok:true,name:c.name})}
if(u.pathname==='/api/customer-login'&&req.method==='POST'){let x=await body(req),d=ensure(read()),email=String(x.email||'').trim().toLowerCase();if(!/^[^\s@]+@gmail\.com$/.test(email))return send(res,400,{error:'اكتب Gmail صحيح مثل example@gmail.com'});let c=d.customers.find(z=>String(z.email).toLowerCase()===email);if(!c){c={id:crypto.randomUUID(),name:'',email,active:true,allowed:['all'],createdAt:new Date().toISOString(),selfRegistered:true,loginCount:0,lastLogin:null};d.customers.unshift(c)}if(c.active===false)return send(res,403,{error:'هذا البريد غير مسموح له بالدخول'});c.loginCount=(c.loginCount||0)+1;c.lastLogin=new Date().toISOString();d.analytics.events.unshift({at:c.lastLogin,visitorId:String(x.visitorId||'').slice(0,100),type:'customer_login',label:c.email,page:'/catalog.html'});write(d);let t=crypto.randomBytes(24).toString('hex');sessions.set('c:'+t,{role:'customer',id:c.id,name:c.name,email:c.email,allowed:c.allowed||['all']});res.setHeader('Set-Cookie',`tp_customer=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);return send(res,200,{ok:true,name:c.name})}
if(u.pathname==='/api/customer-logout'){let m=(req.headers.cookie||'').match(/tp_customer=([^;]+)/);if(m)sessions.delete('c:'+m[1]);res.setHeader('Set-Cookie','tp_customer=; Path=/; Max-Age=0');return send(res,200,{ok:true})}
if(u.pathname==='/api/catalog'&&req.method==='GET'){let c=customerAuth(req);if(!c)return send(res,401,{error:'Login required'});let d=ensure(read()),allowed=c.allowed||['all'],items=allowed.includes('all')?d.items:d.items.filter(x=>allowed.includes(x.category));return send(res,200,{customer:{name:c.name,email:c.email},categories:d.categories,items})}
if(u.pathname==='/api/customer'&&req.method==='POST'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),x=await body(req);if(!x.email||(!x.id&&!x.password))return send(res,400,{error:'Email and password required'});let c=x.id?d.customers.find(z=>z.id===x.id):null;if(c){c.name=String(x.name||'');c.email=String(x.email).trim();c.active=x.active!==false;c.allowed=Array.isArray(x.allowed)?x.allowed:['all'];if(x.password)c.passwordHash=hash(x.password)}else{c={id:crypto.randomUUID(),name:String(x.name||''),email:String(x.email).trim(),passwordHash:hash(x.password),active:true,allowed:Array.isArray(x.allowed)?x.allowed:['all'],createdAt:new Date().toISOString()};d.customers.unshift(c)}write(d);return send(res,200,{ok:true,id:c.id})}
if(u.pathname.startsWith('/api/customer/')&&req.method==='DELETE'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),id=u.pathname.split('/').pop();d.customers=d.customers.filter(x=>x.id!==id);write(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/analytics'&&req.method==='GET'){if(!auth(req))return send(res,401,{error:'Unauthorized'});let d=ensure(read()),a=d.analytics,now=Date.now(),day=86400000;let uniq=a.visits.length,total=a.visits.reduce((n,v)=>n+(v.visits||1),0),today=a.visits.filter(v=>now-new Date(v.lastSeen).getTime()<day).length,week=a.visits.filter(v=>now-new Date(v.lastSeen).getTime()<7*day).length;let clicks={};for(let e of a.events)clicks[e.label]=(clicks[e.label]||0)+1;return send(res,200,{summary:{uniqueVisitors:uniq,totalVisits:total,todayVisitors:today,last7Days:week,leads:a.leads.length},visitors:a.visits.slice(0,500),events:a.events.slice(0,500),leads:a.leads.slice(0,500),topClicks:Object.entries(clicks).sort((a,b)=>b[1]-a[1]).slice(0,20)})}
let p=u.pathname==='/'?'/index.html':u.pathname;if(p.includes('..'))return send(res,403,'Forbidden','text/plain');let f=path.join(PUB,p.replace(/^\/+/,''))if(fs.existsSync(f)&&fs.statSync(f).isFile())return send(res,200,fs.readFileSync(f),mime(f));return send(res,404,'Not found','text/plain')
}catch(e){console.error(e);send(res,500,{error:'Server error'})}}).listen(PORT,()=>console.log(`Together Photographer: http://localhost:${PORT}`));